apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: oracle
  namespace: dotnet-test
spec:
  serviceName: oracle-headless
  replicas: 1
  selector:
    matchLabels:
      app: oracle
  template:
    metadata:
      labels:
        app: oracle
    spec:
      containers:
      - name: oracle
        image: container-registry.oracle.com/database/express:21.3.0-xe
        imagePullPolicy: IfNotPresent
        env:
        - name: ORACLE_PWD
          value: "Middleware123"
        - name: ORACLE_CHARACTERSET
          value: "AL32UTF8"
        ports:
        - containerPort: 1521
        - containerPort: 5500
        volumeMounts:
        - name: middleware-storage
          mountPath: /opt/oracle/oradata
          subPath: oracle
      volumes:
      - name: middleware-storage
        persistentVolumeClaim:
          claimName: middleware-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: oracle-headless
  namespace: dotnet-test
spec:
  clusterIP: None
  selector:
    app: oracle
  ports:
    - protocol: TCP
      port: 1521
      targetPort: 1521
---
apiVersion: v1
kind: Service
metadata:
  name: oracle-service
  namespace: dotnet-test
spec:
  selector:
    app: oracle
  ports:
    - protocol: TCP
      port: 1521
      targetPort: 1521
  type: ClusterIP
